# Generated by Django 4.1.6 on 2023-02-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [migrations.RemoveField(model_name="url", name="textc")]
